name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, mysql
          tools: composer, phpunit

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
